name: On Website Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build_and_deploy_web:
    name: Build & Deploy Flutter to Web
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Enable Web
        run: flutter config --enable-web

      - name: Get packages
        run: flutter pub get

      - name: Build Web Application
        run: flutter build web --release

      - name: Make copy of artifacts
        run: |
          chmod u+x "${{ github.workspace }}/createandcopytofolder.sh"
          bash "${{ github.workspace }}/createandcopytofolder.sh"

      - name: Commit artifacts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Commit the artifacts"
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
